### PR TITLE
Fix #77: Log request URL

### LINKED ISSUE #77: log rest requests and responses
I have spent a lots of time trying to trace why this error happens

```
java.lang.RuntimeException: was not able to find or create a package for X in Repo(X,Y) named Z
```

until at the end I decided to use cURL and create a rest request to see the rest response and hopefully the error (which was not using a license, I switched from a private repo to public OSS repo which won't allow any package without a license)

so it would be better to always log the rest request and response to bintray in DEBUG level so that we are able to trace these kinds of errors easily

### PR DESCRIPTION
**Pull request by travissarles**

### CODE REVIEW

File: src/main/scala/BintrayRepo.scala [hunk 1]
```diff
@@ -48,6 +48,7 @@ case class BintrayRepo(credential: BintrayCredentials, org: Option[String], repo
         }
       if (!exists) sys.error(
         s"was not able to find or create a package for $owner in $repo named $packageName")
+      log.debug(s"Requested vcs URL: $vcs")
```
Comment (2m) [inline src/main/scala/BintrayRepo.scala]: This might help. However I think it would be more interesting to log the request and responses to/from bintray. But that is done by the bintry lib.
